version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
      - xpack.monitoring.collection.enabled=true
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5401"
        tag: "elastic"


  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
      - xpack.monitoring.collection.enabled=true
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - es_data02:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - 9201:9200
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5401"
        tag: "elastic"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL="http://elasticsearch:9200/"
      - xpack.encryptedSavedObjects.encryptionKey="PJrPTJ.gFWRyVriv7HZ2g@BDHY-YXvsHDdXfa@Nt"
      - monitoring.kibana.collection.enabled=false
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    networks:
      - elastic
      - ingress
    depends_on:
      - elasticsearch
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5402"
        tag: "kibana"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.4
    container_name: logstash
    command: logstash
    user: root
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - http.host="0.0.0.0"
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.hosts=["http://elasticsearch:9200"]
      - config.reload.automatic=true
    pid: "host"
    volumes:
      - ./configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/conf.d:/usr/share/logstash/config/conf.d
      - ./configs/logstash:/usr/share/logstash/data
    ports:
      - "5400:5400/udp"
      - "5401:5401/udp"
      - "5402:5402/udp"
    networks:
      - elastic
    depends_on:
      - kibana
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.4
    container_name: filebeat
    command: --strict.perms=false
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - 9009:9000
    volumes:
      - ./data/nginx:/var/log/nginx
      - ./configs/filebeat/modules.d/nginx.yml:/usr/share/filebeat/modules.d/nginx.yml
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elastic
    depends_on:
        - kibana
        - elasticsearch

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - 80:80
    volumes:
        - ./data/nginx/access.log:/var/log/nginx/access.log
        - ./data/nginx/error.log:/var/log/nginx/error.log
        - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
    networks:
      - ingress
      - elastic
    depends_on:
      - kibana
    links:
      - kibana
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5400"
        tag: "nginx"

networks:
  elastic:
  ingress:

volumes: 
  es_data01:
  es_data02:
  logstash:
