version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: nginx-logs
        awslogs-stream: nginx-test-logs
        awslogs-create-group: "true"
    restart: always